services:

  frontend:
    build: './src/frontend'
    container_name: frontend
    environment:
      - 'PORT=3000'
    ports:
      - '3000:3000'
    volumes:
      - './src/frontend:/app'
      - /app/node_modules
    depends_on:
      - 'api'
  admin:
    build: './src/admin'
    container_name: admin
    environment:
      - 'PORT=8080'
    ports:
      - '8080:8080'
    volumes:
      - './src/admin:/app'
    depends_on:
      - 'api'
  api:
    build: './src/api'
    container_name: api
    environment:
      - 'DB_USER=fatec'
      - 'DB_PASSWORD=fatec'
      - 'DB_HOST=database'
      - 'DB_NAME=fatec'
      - 'PORT=8000'
    ports:
      - '8000:8000'
    volumes:
      - './src/api:/app'
    depends_on:
      - 'database'
  database:
    build: './src/database'
    container_name: database
    environment:
      - 'POSTGRES_USER=fatec'
      - 'POSTGRES_PASSWORD=fatec'
      - 'POSTGRES_DB=fatec'
    ports:
      - '5432:5432'
  psql: # docker compose run psql bash && psql -h database -p 5432 -U fatec -d fatec -W
    image: postgres:18-alpine
    container_name: psql
    depends_on:
      - database
