services:

  frontend:
    build: './src/frontend'
    container_name: frontend
    environment:
      - 'PORT=8080'
    ports:
      - '8080:8080'
    volumes:
      - './src/frontend:/app'
    depends_on:
      - 'api'
  api:
    build: './src/api'
    container_name: python
    environment:
      - 'PORT=8000'
    ports:
      - '8000:8000'
    volumes:
      - './src/python:/app'
    depends_on:
      - 'database'
  database:
    build: './src/database'
    container_name: database
    environment:
      - 'POSTGRES_USER=fatec'
      - 'POSTGRES_PASSWORD=fatec'
      - 'POSTGRES_DB=fatec'
    ports:
      - '5432:5432'
  psql: # docker compose run psql bash && psql -h database -p 5432 -U fatec -d fatec -W
    image: postgres:18-alpine
    container_name: psql
    depends_on:
      - database
